export * from './start.js';
export * from './support.js';
export * from './admin.js';
export * from './menu.js';
export * from './contacts.js';
export * from './location.js';
export * from './collaborate.js';
export * from './prepare-materials.js';
export * from './pickup-request.js';
export * from './price.js';
export * from './change-prices.js'
